### ISSUE TITLE
Use explicit marshalling conventions

### ISSUE THREAD

**Issue by SupinePandora43** [WaveEngine/RenderDoc.NET#2]
add `[MarshalAs(UnmanagedType.LPUTF8Str)]`, or at least `[MarshalAs(UnmanagedType.LPStr)]` to `DllImport` method string parameters

**Comment by jcant0n** [comment]
Done,

https://github.com/EvergineTeam/RenderDoc.NET/commit/de394b4b7cad2893ab203da4ec208641943d05da
