### ISSUE TITLE
Use NativeLibrary from >=NetCore3

### ISSUE THREAD

**Issue by SupinePandora43** [WaveEngine/RenderDoc.NET#4]
https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.nativelibrary

**Comment by jcant0n** [comment]
We want to keep support for NetStandard2.0 for older project so we are not going to change it for now. Thanks for your feedback.

**Comment by SupinePandora43** [comment]
> We want to keep support for NetStandard2.0 for older project so we are not going to change it for now. Thanks for your feedback.

You can support netstandard2.0 and use NativeLibrary only for newer TFMs
